In [29]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix, accuracy_score

In [34]:
class Model:

  def __init__(self,datafile):
    self.data = pd.read_csv(datafile)
    self.data = self.data.rename(columns={"Unnamed: 0": "T0"})
        
        #spliting data to Train and test portions
  def split(self, test_size):
    X = self.data.iloc[:1000,:-1]
    y = self.data.iloc[:1000,:]['Class'] 
    self.X_train, self.X_test, self.y_train, self.y_test\
    = train_test_split(X, y, test_size = test_size,\
                       stratify= y, random_state = 0)

            #scaling data 
  def scaler(self):
    sc = StandardScaler()
    self.scaled_X_train = sc.fit_transform(self.X_train)
    self.scaled_X_test = sc.transform(self.X_test)

            #definig the SVM model and corresponding parameters
  def svm(self,kernel_type,hyper_parameter={}):
    
    if kernel_type == 'linear':
      hyper_parameter = hyper_parameter or {'C': 1.0}
      clf = svm.SVC(kernel= kernel_type, class_weight =\
                    'balanced', C = hyper_parameter.get('C'),\
                    random_state=0)

    if kernel_type == 'poly':
      hyper_parameter = hyper_parameter or { 'C': 1.0,\
                                            'degree': 3, 'coef0': 0  }
      clf = svm.SVC(kernel=kernel_type, class_weight =\
                    'balanced', degree = hyper_parameter.get('degree'),\
                    C = hyper_parameter.get('C'),\
                    coef0 = hyper_parameter.get('coef0'), random_state=0)

    if kernel_type == 'rbf':
      hyper_parameter = hyper_parameter or {'C': 1.0,\
                                            'gamma' : 'scale' }
      clf = svm.SVC( kernel=kernel_type, class_weight = 'balanced',\
                    gamma = hyper_parameter.get('gamma'),\
                    C = hyper_parameter.get('C'),random_state=0)
  
    if kernel_type == 'sigmoid':
      hyper_parameter = hyper_parameter or {'C': 1.0 ,\
                                            'gamma' : 'scale',\
                                            'coef0': 0 }
      clf = svm.SVC(kernel=kernel_type, class_weight = 'balanced',\
                    gamma = hyper_parameter.get('gamma'),\
                    C = hyper_parameter.get('C'), \
                    coef0 = hyper_parameter.get('coef0'), random_state=0)
   
    clf.fit(self.scaled_X_train, self.y_train)
    self.y_pred = clf.predict(self.scaled_X_test)
    
            #evaluating the performance of the model

  def performance(self):
    cm = confusion_matrix(self.y_test, self.y_pred)
    ac = accuracy_score(self.y_test, self.y_pred)
    print("Confusion Matrix: \n", cm)
    print("Accuracy:",ac)



    
   

In [35]:
model = Model(datafile= "../data_transformed.csv")

In [36]:
model.data.head()

T0        T1        T2        T3        T4        T5        T6  \
0  169876 -0.611712 -0.769705 -0.149759 -0.224877  2.028577 -2.019887   
1  127467 -0.814682  1.319219  1.329415  0.027273 -0.284871 -0.653985   
2  137900 -0.318193  1.118618  0.969864 -0.127052  0.569563 -0.532484   
3   21513 -1.328271  1.018378  1.775426 -1.574193 -0.117696 -0.457733   
4  134700  1.276712  0.617120 -0.578014  0.879173  0.061706 -1.472002   

         T7        T8        T9  ...       T21       T22       T23       T24  \
0  0.292491 -0.523020  0.358468  ... -0.075208  0.045536  0.380739  0.023440   
1  0.321552  0.435975 -0.704298  ... -0.128619 -0.368565  0.090660  0.401147   
2  0.706252 -0.064966 -0.463271  ... -0.305402 -0.774704 -0.123884 -0.495687   
3  0.681867 -0.031641  0.383872  ... -0.220815 -0.419013 -0.239197  0.009967   
4  0.373692 -0.287204 -0.084482  ... -0.160161 -0.430404 -0.076738  0.258708   

        T25       T26       T27       T28  value  Class  
0 -2.220686 -0.201146  0.066501  0.221180   1.79      0  
1 -0.261034  0.080621  0.162427  0.059456   1.98      0  
2 -0.018148  0.121679  0.249050  0.092516   0.89      0  
3  0.232829  0.814177  0.098797 -0.004273  15.98      0  
4  0.552170  0.370701 -0.034255  0.041709   0.76      0  

[5 rows x 31 columns]

In [37]:
model.split(test_size=0.25)

In [38]:
model.X_train

T0        T1        T2        T3        T4        T5        T6  \
494   32720 -1.697449 -0.081537  1.020244  1.589111  0.402257 -0.989366   
593  164093  2.011990 -1.548324 -0.299211 -1.157665 -1.084316  0.969430   
910  202076  1.835268 -0.476682 -1.445469  0.308313  0.007585 -0.614131   
634   51679 -0.843592 -0.476148  1.261112 -0.548041 -1.098366  0.491156   
136  280080  1.935943 -0.644385 -0.519578  0.141381 -0.645271 -0.193263   
723  231769 -2.151291 -0.924177  1.155999 -0.792443  0.809686 -0.243609   
934  279124 -0.882607  0.283555 -0.787918 -3.788902 -0.057781 -1.984937   
218   49868  0.585355 -2.237053  0.701665 -1.432811 -2.232691 -0.407534   
600   53830 -0.282761  1.132844  0.705547 -0.328320  1.003256  0.312971   
232   21096 -0.678124 -0.186876  2.989155  0.424337 -0.458720  1.996461   
396  104596  1.159177 -0.572358  0.276712 -0.611620 -1.098981 -1.100527   
7     13629 -0.992899  1.430204  1.071256  1.363127  0.116315  0.217868   
30    81969 -1.843619  1.605724  0.569260 -1.500528 -0.643789 -0.421766   
74   132244  1.313522  0.240174 -0.013465  0.175528  0.335200  0.135357   
456    3832 -0.891527 -0.606564  0.621851 -2.809063  1.528988  3.620211   
627    8901 -0.690897  0.828993  1.836637 -1.040730 -0.034200 -1.029891   
790  144266 -0.624946  1.165992  1.143964 -0.027706  0.108731 -0.570701   
251  101325  1.274022  0.002589 -1.156392  0.260460  2.191918  3.604855   
880  129225 -3.257651 -0.776659  1.814048 -0.196673  0.744443 -0.949167   
239  250252  2.016108 -1.111638  0.239716 -0.566659 -1.399912  0.360031   
516   30738  1.155097  0.033699 -0.090881  1.026957  0.435032  0.809886   
422  254952 -0.874169  1.043013 -2.634707 -1.272384  2.666196  3.147507   
207   80446 -0.828876 -1.271519  0.731411 -2.039242 -2.127345 -0.703179   
358  186453 -0.916570  0.964254 -0.372171 -0.706664  0.306086 -0.514987   
230   56557 -2.114572 -0.222286  0.914459  1.367653  0.547705 -1.276232   
768  163895 -0.423046  0.919522  0.847483 -0.670476  1.288797 -0.758415   
733  118924 -2.778900  2.429170  0.130466 -2.098346  0.037122 -0.454429   
172   94686  0.941834  0.104311  0.632207  2.340953  0.653068  2.402285   
756   13312  1.031031 -0.089401  1.387162  1.809605 -0.549154  0.983148   
630  222431  2.053311  0.089735 -1.681836  0.454212  0.298310 -0.953526   
..      ...       ...       ...       ...       ...       ...       ...   
694   68535 -1.312376  1.444763 -0.263747  0.412143  1.955456  4.999902   
334   99669  1.326440 -0.777483  1.347985 -0.614773 -1.745420 -0.507183   
146  175291 -1.441926 -1.306923  1.335368 -2.116169  0.953509 -0.853284   
343   18567 -4.354594  4.068690 -0.114373  0.754473 -0.722937  2.499522   
564  136524 -1.477225 -0.081141  1.199358 -0.360418  1.890102 -1.369992   
402  217571 -0.828056  1.044899  1.088607 -0.686777  0.742313  0.496289   
291  144971  1.939693 -0.186690 -1.774225  0.443863  0.447734 -0.626478   
788  215090 -0.635278  0.901302 -0.742734 -0.365254  0.720473 -0.520949   
897  193188  1.960146 -0.268923 -1.322068  0.304687 -0.169181 -1.038907   
928  184572 -0.186478  0.976338  0.670282 -0.618157  1.167114 -0.538376   
209  167647  2.075871 -0.091094 -1.748496  0.007092  0.578112 -0.408300   
732  130494 -1.296154  1.796180 -0.103716 -0.643974  0.674284  0.703324   
616  240197 -0.716032  1.110061 -0.385563 -1.567362  1.837895 -0.589397   
133  245935  1.977709 -1.254247  0.129673 -0.581969 -1.516882  0.249019   
1    127467 -0.814682  1.319219  1.329415  0.027273 -0.284871 -0.653985   
179  241757 -1.736140  2.271025 -0.692156 -0.804345 -0.144940 -1.405908   
507    9620  1.244914 -0.074293  0.394057 -0.120345  0.042476  0.637983   
458  162626  2.076348  0.185207 -2.290894  1.033680  0.988860 -0.830295   
882  242734  2.048023  0.145918 -1.764051  0.242855  0.638259 -0.412506   
429   47331  1.192315  0.353554  0.425617  0.714525 -0.298443 -0.777867   
110   11516  1.386559 -0.451200  0.542219 -0.449991 -0.771875 -0.250333   
350  139138  1.302378 -0.606529 -0

In [39]:
model.scaler()

C:\Users\Zohaib\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Zohaib\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Zohaib\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.


In [40]:
model.scaled_X_train

array([[-1.29630065, -0.76398464, -0.01897116, ...,  0.66206789,
        -0.07474609, -0.2170324 ],
       [ 0.2725395 ,  0.94244332, -0.89258376, ...,  0.09765645,
        -0.05997034, -0.0250638 ],
       [ 0.72612779,  0.86114728, -0.25431829, ..., -0.03041396,
        -0.09483799,  0.08257208],
       ...,
       [-1.57040254, -0.13707789,  0.30840152, ...,  0.21809093,
         0.25409523, -0.3966767 ],
       [ 0.53370834, -0.17808953, -0.07927719, ...,  0.32733713,
         0.10797854,  1.71863752],
       [ 0.66904562,  0.76253534, -0.88007075, ..., -0.09185943,
        -0.04590947,  0.59384253]])

In [44]:
model.svm(kernel_type="rbf", hyper_parameter = {'C': 1.0,'gamma' : 'scale'})

In [45]:
model.y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [46]:
model.performance()

Confusion Matrix: 
 [[248   1]
 [  1   0]]
Accuracy: 0.992
